/*
 * This file is generated by jOOQ.
 */
package com.example.model.entity;


import lombok.*;
import lombok.experimental.SuperBuilder;

import javax.persistence.*;
import java.math.BigDecimal;


@Getter
@Setter
@ToString
@EqualsAndHashCode(callSuper = false)
@SuperBuilder
@Entity
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "document")
public class DocumentEntity extends AbstractBaseEntity {

    @Column(name = "file_name_in_bucket")
    private String fileNameInBucket;

    @Column(name = "file_name")
    private String fileName;

    private BigDecimal size;

    private String type;

    private String description;

    @ManyToOne
    @JoinColumn(name = "developer_id", referencedColumnName = "id")
    private DeveloperEntity developer;
}
