/*
 * This file is generated by jOOQ.
 */
package com.example.model.entity;


import lombok.*;
import lombok.experimental.SuperBuilder;

import javax.persistence.*;
import java.util.List;


@Getter
@Setter
@ToString
@EqualsAndHashCode(callSuper = false)
@SuperBuilder
@Entity
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "hr")
@PrimaryKeyJoinColumn(name = "id")
public class HrEntity extends AccountEntity{

    private String city;

    @OneToMany(mappedBy = "hr", cascade = {CascadeType.MERGE, CascadeType.REFRESH})
    @ToString.Exclude
    @EqualsAndHashCode.Exclude
    private List<VacancyEntity> vacancies;

    @ManyToOne
    @JoinColumn(name = "company_id", referencedColumnName = "id")
    private CompanyEntity company;
}
