/*
 * This file is generated by jOOQ.
 */
package com.example.model.entity;


import lombok.*;
import lombok.experimental.SuperBuilder;

import javax.persistence.*;


@Getter
@Setter
@ToString
@EqualsAndHashCode(callSuper = false)
@SuperBuilder
@Entity
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "specialization")
public class SpecializationEntity extends AbstractBaseEntity{

    @ManyToOne
    @JoinColumn(name = "developer_id", referencedColumnName = "id")
    private DeveloperEntity developer;

    private String name;
}
